dist: trusty
sudo: required
language: go

services:
  - docker

script:
  - make all

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo $REPO:$TAG:$COMMIT
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag img-mgr amcheste/imgmgr:latest
  - docker push amcheste/imgmgr:latest

